### ISSUE TITLE
Red Hat and derivatives are not fully supported, but we take patches.

### ISSUE THREAD

**Issue by zambon** [opscode-cookbooks/openldap#45]
Hello!
This is from the docs. Could you please elaborate? I'd like to understand what won't work on RHEL and derivatives.

Thanks!

**Comment by tas50** [comment]
I've removed RHEL support in the readme and metadata.  It's not fully functional.  There are several outstanding pull requests to better support RHEL systems, but they need to be rebased and the authors have yet to sign the required iCLA doc.
